name: hw-balancedparens
version: '0.2.0.1'
synopsis: Balanced parentheses
description: Please see README.md
category: Data
author: John Ky
maintainer: newhoggy@gmail.com
copyright: 2016 John Ky
license: BSD3
github: haskell-works/hw-balancedparens
homepage: http://github.com/haskell-works/hw-balancedparens#readme
extra-source-files:
- README.md
ghc-options: -Wall
dependencies:
- base >=4 && <5
- hw-bits >=0.4.0.0
- hw-prim >=0.4.0.0
- vector
library:
  source-dirs: src
  ghc-options:
  - -O2
  - -msse4.2
  exposed-modules:
  - HaskellWorks.Data.BalancedParens
  - HaskellWorks.Data.BalancedParens.BalancedParens
  - HaskellWorks.Data.BalancedParens.Broadword
  - HaskellWorks.Data.BalancedParens.CloseAt
  - HaskellWorks.Data.BalancedParens.Enclose
  - HaskellWorks.Data.BalancedParens.FindClose
  - HaskellWorks.Data.BalancedParens.FindCloseN
  - HaskellWorks.Data.BalancedParens.FindOpen
  - HaskellWorks.Data.BalancedParens.FindOpenN
  - HaskellWorks.Data.BalancedParens.NewCloseAt
  - HaskellWorks.Data.BalancedParens.NewOpenAt
  - HaskellWorks.Data.BalancedParens.OpenAt
  - HaskellWorks.Data.BalancedParens.RangeMinMax
  - HaskellWorks.Data.BalancedParens.RangeMinMax2
  - HaskellWorks.Data.BalancedParens.Simple
  dependencies:
  - hw-excess >=0.2.0.0
  - hw-rankselect-base >=0.2.0.0
  - storable-tuple
tests:
  hw-balancedparens-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec
    - hw-balancedparens
    - hw-rankselect-base >=0.2.0.0
    - QuickCheck
benchmarks:
  bench:
    main: Main.hs
    source-dirs: bench
    ghc-options:
    - -O2
    - -msse4.2
    dependencies:
    - criterion
    - hw-balancedparens
