name: hw-balancedparens
version: '0.2.0.1'
synopsis: Balanced parentheses
description: Balanced parentheses.
category: Data
author: John Ky
maintainer: newhoggy@gmail.com
copyright: 2016 John Ky
license: BSD3
github: haskell-works/hw-balancedparens
homepage: http://github.com/haskell-works/hw-balancedparens#readme
tested-with: GHC == 8.4.2, GHC == 8.2.2, GHC == 8.0.2, GHC == 7.10.3
extra-source-files:
- README.md
ghc-options: -Wall
dependencies:
- base >=4 && <5
- hw-bits >=0.4.0.0 && < 0.8
- hw-prim >=0.4.0.0 && < 0.7
- vector >= 0.12 && < 0.13
library:
  source-dirs: src
  ghc-options:
  - -O2
  - -msse4.2
  exposed-modules:
  - HaskellWorks.Data.BalancedParens
  - HaskellWorks.Data.BalancedParens.BalancedParens
  - HaskellWorks.Data.BalancedParens.Broadword
  - HaskellWorks.Data.BalancedParens.CloseAt
  - HaskellWorks.Data.BalancedParens.Enclose
  - HaskellWorks.Data.BalancedParens.FindClose
  - HaskellWorks.Data.BalancedParens.FindCloseN
  - HaskellWorks.Data.BalancedParens.FindOpen
  - HaskellWorks.Data.BalancedParens.FindOpenN
  - HaskellWorks.Data.BalancedParens.NewCloseAt
  - HaskellWorks.Data.BalancedParens.NewOpenAt
  - HaskellWorks.Data.BalancedParens.OpenAt
  - HaskellWorks.Data.BalancedParens.RangeMinMax
  - HaskellWorks.Data.BalancedParens.RangeMinMax2
  - HaskellWorks.Data.BalancedParens.Simple
  dependencies:
  - hw-excess >=0.2.0.0 && < 0.3
  - hw-rankselect-base >=0.2.0.0 && < 0.4
tests:
  hw-balancedparens-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec >= 2.2 && < 2.6
    - hw-balancedparens
    - hw-rankselect-base >=0.2.0.0 && < 0.4
    - QuickCheck >= 2.10 && < 2.12
    verbatim:
      build-tool-depends: hspec-discover:hspec-discover
benchmarks:
  bench:
    main: Main.hs
    source-dirs: bench
    ghc-options:
    - -O2
    - -msse4.2
    dependencies:
    - criterion >= 1.2 && < 1.5
    - hw-balancedparens
